Initial commit. End of chapter 3 of "Kivy - Interactive applications and games in Python" not working because of:
AttributeError: 'NoneType' object has no attribute 'counter'